Update CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,6 +30,7 @@ jobs:
 
       - name: Run ${{ env.APP_NAME }} with Docker Compose
         run: |
+          set -e
           chmod +x run.sh
           ./run.sh
 
@@ -58,9 +59,8 @@ jobs:
 
       - name: Run unit/integration tests
         run: |
-          set -e
-          npm ci
-          npm run test
+          npm  || { echo "npm ci failed"; exit 1; }
+          npm run test || { echo "npm ci failed"; exit 1; }
 
       - name: Report coverage to Coveralls
         uses: coverallsapp/github-action@v2
